function turbineLoad(windSpeed, maxCapacity, connectedLoad) {

    // ==========================
    // Step 1: Input Validation
    // ==========================
    // Check if all inputs are numbers and within allowed ranges
    if (
        typeof windSpeed !== "number" || windSpeed <= 0 ||        // windSpeed must be > 0
        typeof maxCapacity !== "number" || maxCapacity < 0 ||     // maxCapacity must be >= 0
        typeof connectedLoad !== "number" || connectedLoad <= 0  // connectedLoad must be > 0
    ) {
        return "Invalid Input"; // Reject invalid inputs
    }

    // ==========================
    // Step 2: Calculate Power Generated By Wind Turbine
    // ==========================
    // Basic formula: 1 m/s wind → 10 kW
    let powerGenerated = windSpeed * 10;

    // Cap the generated power to the turbine's maximum capacity
    powerGenerated = Math.min(powerGenerated, maxCapacity);

    // ==========================
    // Step 3: Determine Allowed Load
    // ==========================
    // You cannot use more power than is generated
    let allowedLoad = Math.min(connectedLoad, powerGenerated);

    // ==========================
    // Step 4: Return Results
    // ==========================
    return {
        allowedLoad,      // How much load can actually be supported
        powerGenerated    // How much power was generated
    };
}

// --- Example Usage ---
console.log(turbineLoad(12, 150, 140));